import { Inter } from "next/font/google";
import "./ui/globals.css";
import TopNav from "./ui/topnav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Bangumi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
