import "./ui/globals.css";
import TopNav from "./ui/topnav";

export const metadata = {
  title: "Next Bangumi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-black dark:text-white">
        <TopNav />
        {children}
      </body>
    </html>
  );
}
